"""
This is doctest for matrix_mul function
>>> with open("100-matrix_mul.py", "r") as f:
...     code = f.read()
>>> exec(code)
>>> m_a = [[1, 2], [3, 4]]
>>> m_b = [[5, 6], [7, 8]]
>>> matrix_mul(m_a, m_b)
[[19, 22], [43, 50]]
>>> m_a = [[1, 2], [3, 4], [3, 4]]
>>> m_b = [[5, 6, 1], [7, 8, 2]]
>>> matrix_mul(m_a, m_b)
[[19, 22, 5], [43, 50, 11], [43, 50, 11]]
>>> m_a = "Holberton"
>>> m_b = [[5, 6], [7, 8]]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
TypeError: m_a must be a list
>>> m_a = [[5, 6], [7, 8]]
>>> m_b = "Holberton"
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
TypeError: m_b must be a list
>>> m_a = [1, 2, 3, 4]
>>> m_b = [[5, 6], [7, 8]]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
TypeError: m_a must be a list of lists
>>> m_a = [[5, 6], [7, 8]]
>>> m_b = [1, 2, 3, 4]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
TypeError: m_b must be a list of lists
>>> m_a = [[]]
>>> m_b = [[5, 6], [7, 8]]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
ValueError: m_a can't be empty
>>> m_a = [[5, 6], [7, 8]]
>>> m_b = [[]]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
ValueError: m_b can't be empty
>>> m_a = [[5, "6"], [7, 8]]
>>> m_b = [[5, 6], [7, 8]]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
TypeError: m_a should contain only integers or floats
>>> m_a = [[5, 6], [7, 8]]
>>> m_b = [[5, "6"], [7, 8]]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
TypeError: m_b should contain only integers or floats
>>> m_a = [[5, 6, 10], [7, 8]]
>>> m_b = [[5, 6], [7, 8]]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
TypeError: each row of m_a must be of the same size
>>> m_a = [[5, 6], [7, 8]]
>>> m_b =  [[5, 6, 1], [7, 8]]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
TypeError: each row of m_b must be of the same size
>>> m_a = [[1, 2, 3], [3, 4, 5]]
>>> m_b = [[1, 2], [3, 4]]
>>> matrix_mul(m_a, m_b)
Traceback (most recent call last):
    ...
ValueError: m_a and m_b can't be multiplied

"""
